### ISSUE TITLE
Homozygous results

### ISSUE THREAD

**Issue by ybolon-nmdp** [nmdp-bioinformatics/ngs#110]
Observed results sometimes only produce one allele call (when the expected result is homozygous), so I thought that was the way the observed file shows homozygous calls… until I noticed that sometimes, it does produce two allele calls for homozygous results (ideal scenario), so not sure what is going on when it shows one vs. two.  Can the pipeline distinguish homozygous calls, and what is the threshold?

**Comment by mheuer-nmdp** [comment]
Closing as WontFix, issue with interp, not ngs-tools.
