### ISSUE TITLE
ngs-generate-paired-end-reads generates different file lengths in same pair

### ISSUE THREAD

**Issue by droe-nmdp** [nmdp-bioinformatics/ngs#122]
In version 1.6, the two output paired files are different sizes.

e.g., on NMDP internal 'cloud':
- ngs-generate-paired-end-reads -1 2DL4_0080101_1.fq1.gz -2 2DL4_0080101_1.fq2.gz -r /mnt/common/projects/ngs/kir/fasta/2DL4_0080101.fasta --mean-insert-size 50 --insertion-rate 0 --deletion-rate 0 --substitution-rate 0 --indel-rate 0 --mutation-rate 0 
- wc -l 2DL4_0080101_1.fq*
  16684 2DL4_0080101_1.fq1
  16672 2DL4_0080101_1.fq2

**Comment by mheuer-nmdp** [comment]
One end of the pair could fall out if its location +/- insert size goes out of bounds compared to the reference sequence.
